/**
 * customers.ts — Authenticated route: list customers.
 * Sales reps need this to select a customer when creating a quotation.
 */
import { Router } from 'express';
import { eq } from 'drizzle-orm';
import { z } from 'zod';
import bcrypt from 'bcrypt';

import { db } from '../db/index.js';
import { customers, users } from '../db/schema.js';
import { requireAuth, requireRole } from '../middleware/auth.js';

const router = Router();

router.get('/', requireAuth, async (_req, res) => {
  try {
    const rows = await db
      .select({
        id: customers.id,
        name: customers.name,
        email: customers.email,
        phone: customers.phone,
        tier: customers.tier,
        isActive: customers.isActive,
        createdAt: customers.createdAt,
      })
      .from(customers)
      .where(eq(customers.isActive, true))
      .orderBy(customers.name);
    res.json({ success: true, data: rows });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

const createCustomerSchema = z.object({
  name: z.string().min(1),
  email: z.string().email(),
  phone: z.string().optional(),
  tier: z.enum(['STANDARD', 'PREMIUM', 'ENTERPRISE']).optional(),
});

router.post('/', requireAuth, requireRole(['SALES_REPRESENTATIVE', 'SALES_MANAGER', 'ADMIN']), async (req, res) => {
  try {
    const parsed = createCustomerSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ success: false, error: parsed.error.format() });
    }

    const { name, email, phone, tier } = parsed.data;

    // Check if user email already exists
    const existingUser = await db.select().from(users).where(eq(users.email, email));
    if (existingUser.length > 0) {
      return res.status(409).json({ success: false, error: 'User email already exists' });
    }

    // Auto-generate password
    const password = Math.random().toString(36).slice(-10) + 'A1!'; // Dummy password, in real app would send reset email
    const salt = await bcrypt.genSalt(10);
    const passwordHash = await bcrypt.hash(password, salt);

    const names = name.split(' ');
    const firstName = names[0];
    const lastName = names.slice(1).join(' ') || 'Customer';

    // Run in transaction
    const result = await db.transaction(async (tx) => {
      // 1. Create User
      const [newUser] = await tx.insert(users).values({
        email,
        passwordHash,
        firstName,
        lastName,
        role: 'CUSTOMER',
        status: 'ACTIVE',
      }).returning();

      // 2. Create Customer linked to user
      const [newCustomer] = await tx.insert(customers).values({
        name,
        email,
        phone: phone || null,
        tier: tier || 'STANDARD',
        isActive: true,
        linkedUserId: newUser.id,
      }).returning();

      return newCustomer;
    });

    res.status(201).json({ success: true, data: result, autoGeneratedPassword: password });
  } catch (err) {
    console.error('Create customer error:', err);
    res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

router.get('/:id', requireAuth, async (req, res) => {
  try {
    const [row] = await db.select().from(customers).where(eq(customers.id, String(req.params.id)));
    if (!row) return res.status(404).json({ success: false, error: 'Customer not found' });
    res.json({ success: true, data: row });
  } catch (err) {
    res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

export default router;
