/**
 * customers.ts — Authenticated customer routes for sales users.
 * Sales reps need the list to select a customer when creating a quotation, and
 * the create endpoint to onboard one without waiting on an admin.
 *
 * Creation (customer row + linked portal user) lives in customerService so the
 * admin routes share exactly one schema and one transaction.
 */
import { Router } from 'express';
import { eq } from 'drizzle-orm';

import { db } from '../db/index.js';
import { auditLogs, customers } from '../db/schema.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import {
  createCustomerSchema,
  createCustomerWithPortalUser,
  CustomerServiceError,
  formatZodError,
} from '../services/customers/customerService.js';

const router = Router();

router.get('/', requireAuth, async (_req, res) => {
  try {
    const rows = await db
      .select({
        id: customers.id,
        name: customers.name,
        email: customers.email,
        phone: customers.phone,
        address: customers.address,
        tier: customers.tier,
        isActive: customers.isActive,
        linkedUserId: customers.linkedUserId,
        createdAt: customers.createdAt,
      })
      .from(customers)
      .where(eq(customers.isActive, true))
      .orderBy(customers.name);
    res.json({ success: true, data: rows });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

router.post('/', requireAuth, requireRole(['SALES_REPRESENTATIVE', 'SALES_MANAGER', 'ADMIN']), async (req, res) => {
  try {
    const parsed = createCustomerSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ success: false, error: formatZodError(parsed.error) });
    }

    const result = await createCustomerWithPortalUser(parsed.data);

    // Mirrors the admin route's trail — this endpoint mints `users` rows too,
    // so a sales-created portal login must not be invisible in the audit log.
    await db.insert(auditLogs).values({
      userId: req.user!.id,
      action: 'CUSTOMER_CREATED',
      entityType: 'CUSTOMER',
      entityId: result.customer.id,
      metadata: {
        name: result.customer.name,
        portalUserId: result.portalUser?.id ?? null,
        linkage: result.linkage,
      },
    });

    res.status(201).json({
      success: true,
      data: result.customer,
      portalUser: result.portalUser,
      linkage: result.linkage,
      autoGeneratedPassword: result.generatedPassword,
    });
  } catch (err) {
    if (err instanceof CustomerServiceError) {
      return res.status(err.status).json({ success: false, error: err.message });
    }
    console.error('Create customer error:', err);
    res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

router.get('/:id', requireAuth, async (req, res) => {
  try {
    const [row] = await db.select().from(customers).where(eq(customers.id, String(req.params.id)));
    if (!row) return res.status(404).json({ success: false, error: 'Customer not found' });
    res.json({ success: true, data: row });
  } catch (err) {
    res.status(500).json({ success: false, error: 'Internal server error' });
  }
});

export default router;
