/**
 * customers.ts — Shared shapes for the create-customer flow.
 *
 * Creating a customer provisions its portal (CUSTOMER-role) user in the same
 * request, so both the sales workspace and the admin panel read the same
 * envelope back: the customer row, the portal user it was linked to, and — only
 * when the server minted the login — a password shown exactly once.
 */

export type PortalLinkage = 'CREATED' | 'LINKED' | 'NONE';

export interface PortalUser {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  status?: string;
}

export interface CustomerRecord {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  address?: string | null;
  tier: string;
  isActive: boolean;
  linkedUserId?: string | null;
  portalUser?: PortalUser | null;
}

export interface CustomerCreateResult {
  customer: CustomerRecord;
  portalUser: PortalUser | null;
  linkage: PortalLinkage;
  /** null when an existing login was linked, or the caller chose the password. */
  password: string | null;
}

/**
 * Pulls a displayable string out of an axios error. The API returns
 * `{ error: string }`, but guard against a non-string body so a validation
 * payload can never be rendered as "[object Object]".
 */
export function errorMessage(e: unknown, fallback: string): string {
  const err = (e as { response?: { data?: { error?: unknown } } })?.response?.data?.error;
  if (typeof err === 'string' && err.trim()) return err;
  const message = (e as { message?: unknown })?.message;
  if (typeof message === 'string' && message.trim()) return message;
  return fallback;
}

/** Reads the create/attach envelope off an axios response. */
export function readCustomerResult(data: {
  data: CustomerRecord;
  portalUser?: PortalUser | null;
  linkage?: string;
  autoGeneratedPassword?: string | null;
}): CustomerCreateResult {
  return {
    customer: data.data,
    portalUser: data.portalUser ?? null,
    linkage: (data.linkage ?? 'NONE') as PortalLinkage,
    password: data.autoGeneratedPassword ?? null,
  };
}
